apiVersion: apps/v1
kind: Deployment
metadata:
  name: tunnel
spec:
  selector:
    matchLabels:
      app: tunnel
  template:
    metadata:
      labels:
        app: tunnel
    spec:
      containers:
      - name: tunnel
        image: cloudflare/cloudflared:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
        args:
        - tunnel
        - '--no-autoupdate'
        - '--metrics'
        - 0.0.0.0:3333
        - run
        - '--token'
        - '$(TUNNEL_TOKEN)'
        env:
        - name: TUNNEL_TOKEN
          valueFrom:
            secretKeyRef:
              name: cf-tunnel
              key: token
        livenessProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
        readinessProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
        startupProbe:
          httpGet:
            path: /ready
            port: 3333
            scheme: HTTP
          failureThreshold: 60
          periodSeconds: 10
